# Generated by Django 2.0.4 on 2018-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='', verbose_name='Ссылка')),
                ('link_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_table',
            },
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
